#' Export single-cell data to the Cellucid viewer format
#'
#' `cellucid_prepare()` mirrors the `prepare()` function from the `cellucid`
#' Python package and writes a directory of binary (`.bin`, `.f32`, `.u8`, `.u16`)
#' and JSON manifest files consumed by the Cellucid WebGL viewer.
#'
#' Gene identifiers and `obs` keys must already be 1-180-byte portable ASCII
#' filename components: they begin with a letter or digit, contain only
#' letters, digits, `.`, `_`, or `-`, do not end with `.`, are not Windows
#' device names, and are unique under case-insensitive filesystem comparison.
#'
#' Continuous observation fields, gene expression, and vector fields must
#' contain only finite values. Every nonzero value written as float32, after
#' required embedding/vector scaling, must have an absolute magnitude from
#' `2^-149` through `(2 - 2^-23) * 2^127`; values that would become zero or
#' infinity in the file are rejected before publication.
#' Quantized continuous values and their manifest bounds are derived only after
#' round-tripping through the viewer's float32 domain. Source variation that
#' collapses to one float32 value is rejected rather than advertised as
#' quantized variation that the viewer cannot display. An individual nonzero
#' source value may round to zero when the resulting float32 range remains
#' non-collapsed.
#' Categorical outlier quantiles are generated by Cellucid itself; cells whose
#' category is smaller than `centroid_min_points` carry `NaN`, represented by
#' the reserved integer marker only when those generated quantiles are
#' quantized.
#'
#' @param latent_space Numeric matrix-like of shape `(n_cells, n_dims)`.
#'   Required for per-cell outlier quantile calculations for categorical fields.
#' @param obs A `data.frame` of cell metadata with `n_cells` rows.
#' @param var Optional `data.frame` of feature metadata with `n_genes` rows.
#'   Required if `gene_expression` is provided.
#' @param gene_expression Optional numeric matrix-like of shape
#'   `(n_cells, n_genes)`. Every value must be finite and, for unquantized
#'   output, representable as a nonzero finite float32 value unless it is
#'   exactly zero. Rows are always interpreted as cells; Cellucid never
#'   transposes the matrix or infers its semantic orientation from `var`.
#' @param var_gene_id_column Column name in `var` containing gene identifiers.
#'   Use `NULL` (default) to use `rownames(var)`. Every string, including
#'   `"index"`, names that exact column.
#' @param gene_identifiers Optional character vector specifying which genes to
#'   export. If `NULL`, all genes are exported.
#' @param connectivities Optional adjacency/connectivity matrix of shape
#'   `(n_cells, n_cells)`. Sparse matrices from the `Matrix` package are
#'   supported. Weights must be finite and non-negative, the matrix must be
#'   exactly symmetric in topology and weight, sparse storage must omit zero
#'   values, and the diagonal must be exactly zero.
#' @param out_dir Output directory path. Defaults to `file.path(getwd(),
#'   "exports")`.
#' @param obs_keys Optional character vector of column names in `obs` to export.
#'   If `NULL`, all columns are exported. Numeric observation fields must
#'   contain only finite values and, for unquantized output, every nonzero
#'   value must remain nonzero and finite as float32.
#' @param centroid_outlier_quantile Quantile of distances to keep as inliers
#'   when computing centroids for categorical fields. Set to `NULL` to disable
#'   centroid computation.
#' @param centroid_min_points Minimum number of points in a category required to
#'   compute centroids and outlier quantiles.
#' @param force If `TRUE`, atomically replace an existing output generation. If
#'   `FALSE`, require that `out_dir` does not already exist.
#' @param var_quantization Integer bits for gene expression quantization (`8` or
#'   `16`), or `NULL` for full float32 export. Quantization is derived from the
#'   exact float32 values materialized by the viewer; a native-double range
#'   that collapses to one float32 value is rejected. Individual source values
#'   may round to zero when the float32 range remains non-collapsed.
#' @param obs_continuous_quantization Integer bits for continuous obs field
#'   quantization (`8` or `16`), or `NULL` for full float32 export.
#'   Quantization is derived from the exact float32 values materialized by the
#'   viewer; a native-double range that collapses to one float32 value is
#'   rejected. Individual source values may round to zero when the float32
#'   range remains non-collapsed.
#' @param obs_categorical_dtype Required exact categorical code storage:
#'   `"uint8"` or `"uint16"`.
#' @param compression Optional gzip compression level (`1`-`9`). Use `NULL` to
#'   disable compression.
#' @param dataset_name Required non-empty dataset name without leading or
#'   trailing whitespace for `dataset_identity.json`.
#' @param dataset_description Dataset description. Defaults to an empty string.
#' @param dataset_id Required portable dataset identifier.
#' @param source_name Optional data source name for metadata. If supplied,
#'   `source_url` and `source_citation` are also required.
#' @param source_url Optional data source URL for metadata. If supplied,
#'   `source_name` and `source_citation` are also required.
#' @param source_citation Optional citation text for metadata. If supplied,
#'   `source_name` and `source_url` are also required.
#' @param X_umap_1d Optional 1D embedding matrix of shape `(n_cells, 1)`.
#' @param X_umap_2d Optional 2D embedding matrix of shape `(n_cells, 2)`.
#' @param X_umap_3d Optional 3D embedding matrix of shape `(n_cells, 3)`.
#' @param vector_fields Optional named list of per-cell displacement vectors.
#'   Each element must be a numeric vector (1D) or matrix with 1/2/3 columns and
#'   `n_cells` rows.
#' @param vector_field_default Exact vector-field identifier to select by
#'   default. Required when `vector_fields` contains more than one field.
#'
#' @return Invisibly returns `NULL`. Called for its side effects (file export).
#' @export
cellucid_prepare <- function(
    latent_space = NULL,
    obs = NULL,
    var = NULL,
    gene_expression = NULL,
    var_gene_id_column = NULL,
    gene_identifiers = NULL,
    connectivities = NULL,
    out_dir = file.path(getwd(), "exports"),
    obs_keys = NULL,
    centroid_outlier_quantile = 0.95,
    centroid_min_points = 10,
    force = FALSE,
    var_quantization = NULL,
    obs_continuous_quantization = NULL,
    obs_categorical_dtype,
    compression = NULL,
    dataset_name = NULL,
    dataset_description = "",
    dataset_id = NULL,
    source_name = NULL,
    source_url = NULL,
    source_citation = NULL,
    X_umap_1d = NULL,
    X_umap_2d = NULL,
    X_umap_3d = NULL,
    vector_fields = NULL,
    vector_field_default = NULL
) {
  manifest_format_version <- "compact_v1"
  obs_binary_dirname <- "obs"
  var_binary_dirname <- "var"
  connectivity_binary_dirname <- "connectivity"

  force <- .validate_force(force)
  compression <- .normalize_compression(compression)
  obs_categorical_dtype <- .validate_obs_categorical_dtype(
    obs_categorical_dtype
  )
  dataset_id <- .validate_dataset_id(dataset_id)
  dataset_name <- .validate_required_string(dataset_name, "dataset_name")
  dataset_description <- .validate_string(
    dataset_description,
    "dataset_description"
  )
  source_info <- .validate_source_identity(
    source_name,
    source_url,
    source_citation
  )

  if (!is.null(var_quantization)) {
    var_quantization <- .validate_quantization_bits(
      var_quantization,
      arg = "var_quantization"
    )
  }
  if (!is.null(obs_continuous_quantization)) {
    obs_continuous_quantization <- .validate_quantization_bits(
      obs_continuous_quantization,
      arg = "obs_continuous_quantization"
    )
  }
  centroid_outlier_quantile <- .validate_centroid_outlier_quantile(
    centroid_outlier_quantile
  )
  centroid_min_points <- .validate_positive_integer(
    centroid_min_points,
    "centroid_min_points"
  )

  final_out_dir <- .validate_output_path(out_dir)
  out_dir <- .begin_staged_output(final_out_dir, force)
  staged_output_is_owned <- TRUE
  on.exit({
    if (staged_output_is_owned && dir.exists(out_dir)) {
      unlink(out_dir, recursive = TRUE, force = TRUE)
    }
  }, add = TRUE)
  .dir_create(out_dir)

  obs_binary_dir <- file.path(out_dir, obs_binary_dirname)
  .dir_create(obs_binary_dir)

  embeddings_in <- list(
    `1` = X_umap_1d,
    `2` = X_umap_2d,
    `3` = X_umap_3d
  )
  embeddings <- .collect_embeddings(embeddings_in)
  n_cells <- .validate_embeddings(embeddings)
  connectivity_edges <- NULL
  if (!is.null(connectivities)) {
    connectivity_edges <- .validate_connectivity_edges(
      connectivities = connectivities,
      n_cells = n_cells
    )
  }

  normalization_info <- list()
  for (dim in names(embeddings)) {
    if (any(!is.finite(embeddings[[dim]]))) {
      stop(
        "X_umap_", dim, "d contains non-finite values (NA/NaN/Inf). ",
        "Please filter or impute before export."
      )
    }
    normalized <- .normalize_embedding(embeddings[[dim]])
    embeddings[[dim]] <- normalized$coords
    normalization_info[[dim]] <- normalized$info
  }

  available_dimensions <- sort(as.integer(names(embeddings)))
  default_dimension <- if (3L %in% available_dimensions) {
    3L
  } else if (2L %in% available_dimensions) {
    2L
  } else {
    1L
  }

  # Save embeddings
  for (dim in available_dimensions) {
    file_base <- file.path(out_dir, sprintf("points_%dd.bin", dim))
    .write_float32_matrix_row_major(file_base, embeddings[[as.character(dim)]], compression = compression)
  }

  if (is.null(latent_space)) {
    stop("latent_space is required for outlier quantile calculation.")
  }
  latent <- .as_dense_matrix(latent_space, name = "latent_space")
  if (nrow(latent) != n_cells) {
    stop(
      "Latent space has ", nrow(latent), " cells, but embeddings have ", n_cells, " cells."
    )
  }

  if (!is.data.frame(obs)) {
    stop("obs must be a data.frame.", call. = FALSE)
  }
  if (nrow(obs) != n_cells) {
    stop("obs has ", nrow(obs), " rows, but embeddings have ", n_cells, " cells.")
  }

  if (is.null(obs_keys)) {
    obs_keys <- names(obs)
  }
  .validate_character_vector(obs_keys, what = "obs_keys")
  if (anyDuplicated(obs_keys)) {
    stop("obs_keys must not contain duplicate field names.", call. = FALSE)
  }
  missing <- setdiff(obs_keys, names(obs))
  if (length(missing) > 0) {
    stop(
      "obs_keys contain columns not in obs: ",
      paste(missing, collapse = ", "),
      ". Available columns: ",
      paste(names(obs), collapse = ", ")
    )
  }

  # Collect lightweight metadata for obs fields (used in dataset identity)
  obs_field_summaries <- lapply(
    obs_keys,
    function(key) .summarize_obs_field(
      obs[[key]],
      key = key,
      obs_continuous_quantization = obs_continuous_quantization,
      obs_categorical_dtype = obs_categorical_dtype
    )
  )

  # Vector fields (optional)
  vector_fields_identity <- NULL
  if (!is.null(vector_fields)) {
    vector_result <- .export_vector_fields(
      vector_fields = vector_fields,
      embeddings = embeddings,
      normalization_info = normalization_info,
      out_dir = out_dir,
      compression = compression,
      vector_field_default = vector_field_default
    )
    vector_fields_identity <- vector_result$identity
  } else if (!is.null(vector_field_default)) {
    stop(
      "vector_field_default requires vector_fields.",
      call. = FALSE
    )
  }

  # ===========================================================================
  # OBS EXPORT
  # ===========================================================================
  obs_manifest_path <- file.path(out_dir, "obs_manifest.json")
  obs_export <- .export_obs(
    obs = obs,
    obs_keys = obs_keys,
    latent = latent,
    embeddings = embeddings,
    obs_binary_dir = obs_binary_dir,
    obs_binary_dirname = obs_binary_dirname,
    centroid_outlier_quantile = centroid_outlier_quantile,
    centroid_min_points = centroid_min_points,
    obs_continuous_quantization = obs_continuous_quantization,
    obs_categorical_dtype = obs_categorical_dtype,
    compression = compression
  )

  obs_manifest_payload <- list(
    `_format` = manifest_format_version,
    n_points = as.integer(n_cells),
    centroid_outlier_quantile = if (!is.null(centroid_outlier_quantile)) {
      centroid_outlier_quantile
    } else {
      NULL
    },
    latent_key = "latent_space",
    compression = if (!is.null(compression)) compression else NULL,
    `_obsSchemas` = obs_export$schemas,
    `_continuousFields` = obs_export$continuous_fields,
    `_categoricalFields` = obs_export$categorical_fields
  )
  .write_json(obs_manifest_path, obs_manifest_payload, pretty = FALSE)

  identity_obs_fields <- .identity_obs_fields_from_compact_manifest(
    obs_manifest_payload
  )
  centroid_quantile_matches <- if (is.null(centroid_outlier_quantile)) {
    is.null(obs_manifest_payload$centroid_outlier_quantile)
  } else {
    is.numeric(obs_manifest_payload$centroid_outlier_quantile) &&
      length(obs_manifest_payload$centroid_outlier_quantile) == 1L &&
      !is.na(obs_manifest_payload$centroid_outlier_quantile) &&
      obs_manifest_payload$centroid_outlier_quantile ==
        centroid_outlier_quantile
  }
  compression_matches <- if (is.null(compression)) {
    is.null(obs_manifest_payload$compression)
  } else {
    is.numeric(obs_manifest_payload$compression) &&
      length(obs_manifest_payload$compression) == 1L &&
      !is.na(obs_manifest_payload$compression) &&
      obs_manifest_payload$compression == compression
  }
  if (
    !is.numeric(obs_manifest_payload$n_points) ||
      length(obs_manifest_payload$n_points) != 1L ||
      is.na(obs_manifest_payload$n_points) ||
      obs_manifest_payload$n_points != n_cells ||
      !centroid_quantile_matches ||
      !identical(obs_manifest_payload$latent_key, "latent_space") ||
      !compression_matches
  ) {
    stop(
      "Observation manifest ",
      obs_manifest_path,
      " does not match the staged export settings.",
      call. = FALSE
    )
  }
  ordered_obs_field_summaries <- c(
    Filter(
      function(field_info) identical(field_info$kind, "continuous"),
      obs_field_summaries
    ),
    Filter(
      function(field_info) identical(field_info$kind, "category"),
      obs_field_summaries
    )
  )
  expected_identity_obs_fields <- lapply(
    ordered_obs_field_summaries,
    function(field_info) {
      entry <- list(key = field_info$key, kind = field_info$kind)
      if (identical(field_info$kind, "category")) {
        entry$n_categories <- as.integer(field_info$category_count)
      }
      entry
    }
  )
  if (!identical(identity_obs_fields, expected_identity_obs_fields)) {
    stop(
      "Observation manifest ",
      obs_manifest_path,
      " fields do not match the staged observation fields.",
      call. = FALSE
    )
  }

  # ===========================================================================
  # VAR (GENE EXPRESSION) EXPORT
  # ===========================================================================
  genes_to_export <- character(0)
  if (!is.null(gene_expression)) {
    if (!is.data.frame(var)) {
      stop(
        "var must be a data.frame when gene_expression is supplied.",
        call. = FALSE
      )
    }

    gene_expression <- .as_matrix_like(gene_expression, name = "gene_expression")
    if (nrow(gene_expression) != n_cells) {
      stop("gene_expression has ", nrow(gene_expression), " cells, but embeddings have ", n_cells, " cells.")
    }
    if (nrow(var) != ncol(gene_expression)) {
      stop("var has ", nrow(var), " rows, but gene_expression has ", ncol(gene_expression), " genes.")
    }

    all_gene_ids <- .extract_gene_ids(var, var_gene_id_column)
    gene_id_to_idx <- stats::setNames(seq_along(all_gene_ids), all_gene_ids)

    if (is.null(gene_identifiers)) {
      genes_to_export <- all_gene_ids
    } else {
      .validate_character_vector(
        gene_identifiers,
        what = "gene_identifiers"
      )
      if (anyDuplicated(gene_identifiers)) {
        stop(
          "gene_identifiers must not contain duplicate identifiers.",
          call. = FALSE
        )
      }
      missing_genes <- setdiff(gene_identifiers, names(gene_id_to_idx))
      if (length(missing_genes) > 0) {
        stop(
          "gene_identifiers contains identifiers not found in var: ",
          paste(utils::head(missing_genes, 5), collapse = ", "),
          if (length(missing_genes) > 5) "..." else "",
          call. = FALSE
        )
      }
      genes_to_export <- gene_identifiers
    }

    var_manifest_path <- file.path(out_dir, "var_manifest.json")
    var_binary_dir <- file.path(out_dir, var_binary_dirname)
    .dir_create(var_binary_dir)

    var_manifest_fields <- vector("list", length(genes_to_export))
    safe_gene_ids <- .assert_unique_filename_components(genes_to_export, what = "Gene identifiers")

    for (idx in seq_along(genes_to_export)) {
      gene_id <- genes_to_export[[idx]]
      gene_idx <- unname(gene_id_to_idx[[gene_id]])
      safe_gene_id <- safe_gene_ids[[idx]]

      values <- .get_gene_column(gene_expression, gene_idx, n_cells = n_cells)

      if (!is.null(var_quantization)) {
        q <- .quantize_continuous(
          values,
          bits = var_quantization,
          field_name = gene_id
        )
        ext <- if (var_quantization == 8L) "u8" else "u16"
        value_path <- file.path(var_binary_dir, sprintf("%s.values.%s", safe_gene_id, ext))
        if (var_quantization == 8L) {
          .write_uint8(value_path, q$quantized, compression = compression)
        } else {
          .write_uint16(value_path, q$quantized, compression = compression)
        }
        var_manifest_fields[[idx]] <- list(gene_id, q$min_val, q$max_val)
      } else {
        value_path <- file.path(var_binary_dir, sprintf("%s.values.f32", safe_gene_id))
        .write_float32_vector(value_path, values, compression = compression)
        var_manifest_fields[[idx]] <- list(gene_id)
      }
    }

    gz_suffix <- if (!is.null(compression)) ".gz" else ""
    var_schema <- if (!is.null(var_quantization)) {
      ext <- if (var_quantization == 8L) "u8" else "u16"
      dtype_str <- if (var_quantization == 8L) "uint8" else "uint16"
      list(
        kind = "continuous",
        pathPattern = sprintf("%s/{key}.values.%s%s", var_binary_dirname, ext, gz_suffix),
        ext = ext,
        dtype = dtype_str,
        quantized = TRUE,
        quantizationBits = var_quantization
      )
    } else {
      list(
        kind = "continuous",
        pathPattern = sprintf("%s/{key}.values.f32%s", var_binary_dirname, gz_suffix),
        ext = "f32",
        dtype = "float32",
        quantized = FALSE
      )
    }

    var_manifest_payload <- list(
      `_format` = manifest_format_version,
      n_points = as.integer(n_cells),
      var_gene_id_column = var_gene_id_column,
      compression = if (!is.null(compression)) compression else NULL,
      quantization = if (!is.null(var_quantization)) var_quantization else NULL,
      `_varSchema` = var_schema,
      fields = var_manifest_fields
    )
    .write_json(var_manifest_path, var_manifest_payload, pretty = FALSE)
  }

  # ===========================================================================
  # CONNECTIVITY EXPORT
  # ===========================================================================
  connectivity_meta <- list(
    n_edges = NULL,
    max_neighbors = NULL,
    index_dtype = NULL
  )

  if (!is.null(connectivities)) {
    if (is.null(connectivity_edges)) {
      stop("Validated connectivity edge pairs are unavailable.", call. = FALSE)
    }
    connectivity_manifest_path <- file.path(
      out_dir,
      "connectivity_manifest.json"
    )
    connectivity_meta$n_edges <- connectivity_edges$n_edges
    connectivity_meta$max_neighbors <- connectivity_edges$max_neighbors
    connectivity_meta$index_dtype <- connectivity_edges$index_dtype
    connectivity_binary_dir <- file.path(out_dir, connectivity_binary_dirname)
    .dir_create(connectivity_binary_dir)

    .write_connectivity_edges(
      connectivity_edges = connectivity_edges,
      out_dir = connectivity_binary_dir,
      compression = compression
    )

    sources_fname <- "edges.src.bin"
    dests_fname <- "edges.dst.bin"
    weights_fname <- "edges.weights.f64.bin"
    manifest_sources <- paste0(connectivity_binary_dirname, "/", sources_fname)
    manifest_dests <- paste0(connectivity_binary_dirname, "/", dests_fname)
    manifest_weights <- paste0(connectivity_binary_dirname, "/", weights_fname)
    if (!is.null(compression)) {
      manifest_sources <- paste0(manifest_sources, ".gz")
      manifest_dests <- paste0(manifest_dests, ".gz")
      manifest_weights <- paste0(manifest_weights, ".gz")
    }

    connectivity_manifest_payload <- list(
      format = "edge_pairs",
      n_cells = as.integer(n_cells),
      n_edges = connectivity_edges$n_edges,
      max_neighbors = connectivity_edges$max_neighbors,
      index_bytes = connectivity_edges$index_bytes,
      index_dtype = connectivity_edges$index_dtype,
      sourcesPath = manifest_sources,
      destinationsPath = manifest_dests,
      weightsPath = manifest_weights,
      weight_dtype = "float64",
      weight_bytes = 8L,
      compression = if (!is.null(compression)) compression else NULL
    )
    .write_json(connectivity_manifest_path, connectivity_manifest_payload, pretty = FALSE)
  }

  # ===========================================================================
  # DATASET IDENTITY
  # ===========================================================================
  identity_path <- file.path(out_dir, "dataset_identity.json")
  cellucid_version <- as.character(utils::packageVersion("cellucid"))

  n_genes <- if (!is.null(gene_expression)) {
    as.integer(length(genes_to_export))
  } else {
    0L
  }

  n_obs_fields <- length(identity_obs_fields)
  n_categorical_fields <- sum(
    vapply(
      identity_obs_fields,
      function(field_info) identical(field_info$kind, "category"),
      logical(1)
    )
  )
  n_continuous_fields <- sum(
    vapply(
      identity_obs_fields,
      function(field_info) identical(field_info$kind, "continuous"),
      logical(1)
    )
  )

  export_settings <- list(
    compression = if (!is.null(compression)) compression else NULL,
    var_quantization = if (!is.null(var_quantization)) var_quantization else NULL,
    obs_continuous_quantization = if (!is.null(obs_continuous_quantization)) {
      obs_continuous_quantization
    } else {
      NULL
    },
    obs_categorical_dtype = obs_categorical_dtype
  )

  gz_suffix <- if (!is.null(compression)) ".gz" else ""
  embeddings_meta <- list(
    available_dimensions = I(available_dimensions),
    default_dimension = default_dimension,
    files = list()
  )
  for (dim in available_dimensions) {
    embeddings_meta$files[[sprintf("%dd", dim)]] <- sprintf("points_%dd.bin%s", dim, gz_suffix)
  }

  identity_payload <- list(
    version = 2,
    id = dataset_id,
    name = dataset_name,
    description = dataset_description,
    created_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
    cellucid_data_version = cellucid_version,
    stats = list(
      n_cells = as.integer(n_cells),
      n_genes = as.integer(n_genes),
      n_obs_fields = as.integer(n_obs_fields),
      n_categorical_fields = as.integer(n_categorical_fields),
      n_continuous_fields = as.integer(n_continuous_fields),
      has_connectivity = !is.null(connectivity_meta$n_edges),
      n_edges = connectivity_meta$n_edges
    ),
    embeddings = embeddings_meta,
    obs_fields = identity_obs_fields,
    export_settings = export_settings
  )

  if (!is.null(source_info)) {
    identity_payload$source <- source_info
  }
  if (!is.null(vector_fields_identity)) {
    identity_payload$vector_fields <- vector_fields_identity
  }

  .write_json(identity_path, identity_payload, pretty = 2)
  .publish_staged_output(out_dir, final_out_dir, force)
  staged_output_is_owned <- FALSE

  invisible(NULL)
}

.validate_force <- function(force) {
  if (
    !is.logical(force) ||
      length(force) != 1L ||
      is.na(force) ||
      is.object(force)
  ) {
    stop("force must be exactly TRUE or FALSE.", call. = FALSE)
  }
  force
}

.validate_string <- function(value, arg) {
  if (
    !is.character(value) ||
      length(value) != 1L ||
      is.na(value) ||
      is.object(value)
  ) {
    stop(arg, " must be exactly one string.", call. = FALSE)
  }
  value
}

.validate_required_string <- function(value, arg) {
  value <- .validate_string(value, arg)
  if (!nzchar(value) || !identical(value, trimws(value))) {
    stop(
      arg,
      " must be one non-empty string without leading or trailing whitespace.",
      call. = FALSE
    )
  }
  value
}

.validate_dataset_id <- function(value) {
  .safe_filename_component(value, what = "dataset_id")
}

.validate_source_identity <- function(name, url, citation) {
  values <- list(
    source_name = name,
    source_url = url,
    source_citation = citation
  )
  present <- !vapply(values, is.null, logical(1))
  if (!any(present)) {
    return(NULL)
  }
  if (!all(present)) {
    stop(
      "source_name, source_url, and source_citation must either all be ",
      "supplied or all be NULL.",
      call. = FALSE
    )
  }
  list(
    name = .validate_required_string(name, "source_name"),
    url = .validate_required_string(url, "source_url"),
    citation = .validate_required_string(citation, "source_citation")
  )
}

.validate_obs_categorical_dtype <- function(value) {
  supported <- c("uint8", "uint16")
  if (
    !is.character(value) ||
      length(value) != 1L ||
      is.na(value) ||
      is.object(value) ||
      !value %in% supported
  ) {
    stop(
      "obs_categorical_dtype must be exactly one of \"uint8\" or \"uint16\".",
      call. = FALSE
    )
  }
  value
}

.normalize_compression <- function(compression) {
  if (is.null(compression)) {
    return(NULL)
  }
  if (
    !is.numeric(compression) ||
      length(compression) != 1L ||
      is.na(compression) ||
      !is.finite(compression) ||
      compression != floor(compression) ||
      compression < 1 ||
      compression > 9
  ) {
    stop(
      "compression must be NULL or one integer from 1 to 9.",
      call. = FALSE
    )
  }
  compression
}

.validate_quantization_bits <- function(bits, arg) {
  if (
    !is.numeric(bits) ||
      length(bits) != 1L ||
      is.na(bits) ||
      !is.finite(bits) ||
      !(bits %in% c(8, 16))
  ) {
    stop(arg, " must be exactly 8 or 16.", call. = FALSE)
  }
  bits
}

.validate_centroid_outlier_quantile <- function(value) {
  if (is.null(value)) {
    return(NULL)
  }
  if (
    !is.numeric(value) ||
      length(value) != 1L ||
      is.na(value) ||
      !is.finite(value) ||
      value <= 0.5 ||
      value >= 1
  ) {
    stop(
      "centroid_outlier_quantile must be NULL or one finite number ",
      "strictly between 0.5 and 1.",
      call. = FALSE
    )
  }
  value
}

.validate_positive_integer <- function(value, arg) {
  if (
    !is.numeric(value) ||
      length(value) != 1L ||
      is.na(value) ||
      !is.finite(value) ||
      value != floor(value) ||
      value < 1 ||
      value > .Machine$integer.max
  ) {
    stop(arg, " must be one positive integer.", call. = FALSE)
  }
  as.integer(value)
}

.validate_character_vector <- function(values, what) {
  if (!is.character(values) || !is.null(dim(values))) {
    stop(what, " must be a character vector.", call. = FALSE)
  }
  if (anyNA(values) || any(!nzchar(values))) {
    stop(
      what,
      " must contain only non-missing, non-empty strings.",
      call. = FALSE
    )
  }
  invisible(values)
}

.validate_output_path <- function(path) {
  path <- .validate_required_string(path, "out_dir")
  normalized <- normalizePath(path, winslash = "/", mustWork = FALSE)
  protected <- unique(c(
    "/",
    normalizePath(getwd(), winslash = "/", mustWork = TRUE),
    normalizePath(path.expand("~"), winslash = "/", mustWork = TRUE)
  ))
  if (normalized %in% protected) {
    stop(
      "out_dir must name a dedicated dataset output directory.",
      call. = FALSE
    )
  }
  normalized
}

.begin_staged_output <- function(final_path, force) {
  if (file.exists(final_path) && !force) {
    stop(
      "out_dir already exists; set force = TRUE to replace the complete ",
      "generation.",
      call. = FALSE
    )
  }
  parent <- dirname(final_path)
  .dir_create(parent)
  stage <- tempfile(
    pattern = paste0(".", basename(final_path), ".stage-"),
    tmpdir = parent
  )
  if (!dir.create(stage, recursive = FALSE, showWarnings = FALSE)) {
    stop("Could not create the staged output directory.", call. = FALSE)
  }
  normalizePath(stage, winslash = "/", mustWork = TRUE)
}

.publish_staged_output <- function(stage, final_path, force) {
  existing <- file.exists(final_path)
  if (existing && !force) {
    stop(
      "out_dir already exists; set force = TRUE to replace the complete ",
      "generation.",
      call. = FALSE
    )
  }

  backup <- NULL
  if (existing) {
    backup <- tempfile(
      pattern = paste0(".", basename(final_path), ".previous-"),
      tmpdir = dirname(final_path)
    )
    if (!file.rename(final_path, backup)) {
      stop(
        "Could not move the existing output generation aside for replacement.",
        call. = FALSE
      )
    }
  }

  if (!file.rename(stage, final_path)) {
    if (!is.null(backup)) {
      restored <- file.rename(backup, final_path)
      if (!restored) {
        stop(
          "Could not publish the staged generation or restore the previous ",
          "generation.",
          call. = FALSE
        )
      }
    }
    stop("Could not publish the staged output generation.", call. = FALSE)
  }

  if (!is.null(backup)) {
    unlink(backup, recursive = TRUE, force = TRUE)
    if (file.exists(backup)) {
      stop(
        "The new generation is published, but the previous generation could ",
        "not be removed.",
        call. = FALSE
      )
    }
  }
  invisible(final_path)
}

.dir_create <- function(path) {
  if (!dir.exists(path)) {
    created <- dir.create(path, recursive = TRUE, showWarnings = FALSE)
    if (!created && !dir.exists(path)) {
      stop("Could not create directory: ", path, call. = FALSE)
    }
  }
  invisible(path)
}

.safe_filename_component <- function(name, what = "Filename component") {
  name <- .validate_required_string(name, what)
  if (
    !grepl("^[A-Za-z0-9][A-Za-z0-9._-]*$", name) ||
      grepl("\\.$", name) ||
      nchar(name, type = "bytes") > 180L
  ) {
    stop(
      what, " '", name, "' is not a portable identifier. Use ",
      "1-180 ASCII letters, numbers, '.', '_', or '-', beginning with a ",
      "letter or number and not ending with '.'.",
      call. = FALSE
    )
  }
  device_base <- toupper(strsplit(name, ".", fixed = TRUE)[[1]][[1]])
  if (
    device_base %in% c("CON", "PRN", "AUX", "NUL") ||
      grepl("^(COM|LPT)[1-9]$", device_base)
  ) {
    stop(
      what, " '", name, "' is reserved on Windows.",
      call. = FALSE
    )
  }
  name
}

.assert_unique_filename_components <- function(keys, what) {
  if (!is.character(keys) || anyNA(keys) || any(!nzchar(keys))) {
    stop(what, " must contain only non-empty strings.", call. = FALSE)
  }
  safe <- vapply(keys, .safe_filename_component, character(1))

  folded <- tolower(safe)
  dup_safe <- unique(folded[duplicated(folded)])
  if (length(dup_safe) == 0L) {
    return(invisible(safe))
  }

  collision_lines <- character(0)
  for (safe_key in dup_safe) {
    originals <- unique(keys[folded == safe_key])
    preview <- paste(sprintf("'%s'", utils::head(originals, 5)), collapse = ", ")
    if (length(originals) > 5L) {
      preview <- paste0(preview, ", ...")
    }
    collision_lines <- c(collision_lines, sprintf("  - '%s' <- %s", safe_key, preview))
  }

  stop(
    what,
    " contains names that collide on case-insensitive filesystems.\n",
    "Rename the identifiers. Collisions:\n",
    paste(collision_lines, collapse = "\n"),
    call. = FALSE
  )
}

.as_dense_matrix <- function(x, name) {
  if (inherits(x, "Matrix")) {
    x <- as.matrix(x)
  } else if (
    is.data.frame(x) &&
      all(vapply(x, function(column) {
        is.numeric(column) && !is.object(column)
      }, logical(1)))
  ) {
    x <- as.matrix(x)
  } else if (
    !is.matrix(x) ||
      !is.numeric(x) ||
      is.object(x)
  ) {
    stop(name, " must be a finite real numeric matrix.", call. = FALSE)
  }
  storage.mode(x) <- "double"
  if (anyNA(x) || any(!is.finite(x))) {
    stop(name, " must contain only finite values.", call. = FALSE)
  }
  x
}

.as_matrix_like <- function(x, name) {
  if (inherits(x, "Matrix")) {
    if (!inherits(x, "dMatrix")) {
      stop(name, " must contain real numeric values.", call. = FALSE)
    }
    values <- x@x
    if (anyNA(values) || any(!is.finite(values))) {
      stop(
        name,
        " must not contain infinite or missing sparse values.",
        call. = FALSE
      )
    }
    return(x)
  } else if (
    is.data.frame(x) &&
      all(vapply(x, function(column) {
        is.numeric(column) && !is.object(column)
      }, logical(1)))
  ) {
    x <- as.matrix(x)
  } else if (
    !is.matrix(x) ||
      !is.numeric(x) ||
      is.object(x)
  ) {
    stop(name, " must be a real numeric matrix.", call. = FALSE)
  }
  if (anyNA(x) || any(!is.finite(x))) {
    stop(name, " must contain only finite values.", call. = FALSE)
  }
  storage.mode(x) <- "double"
  x
}

.collect_embeddings <- function(embeddings_in) {
  embeddings <- list()
  for (dim_chr in names(embeddings_in)) {
    x <- embeddings_in[[dim_chr]]
    if (is.null(x)) {
      next
    }
    dim_int <- as.integer(dim_chr)
    if (
      is.numeric(x) &&
        !is.object(x) &&
        is.null(dim(x)) &&
        dim_int == 1L
    ) {
      x <- matrix(x, ncol = 1L)
    } else if (
      is.data.frame(x) &&
        all(vapply(x, function(column) {
          is.numeric(column) && !is.object(column)
        }, logical(1)))
    ) {
      x <- as.matrix(x)
    } else if (inherits(x, "Matrix")) {
      x <- as.matrix(x)
    } else if (
      !is.matrix(x) ||
        !is.numeric(x) ||
        is.object(x)
    ) {
      stop(
        "X_umap_", dim_chr,
        "d must be a finite real numeric matrix.",
        call. = FALSE
      )
    } else {
      x <- unclass(x)
    }
    storage.mode(x) <- "double"
    embeddings[[dim_chr]] <- x
  }
  if (length(embeddings) == 0) {
    stop("At least one embedding must be provided: X_umap_1d, X_umap_2d, or X_umap_3d.")
  }
  embeddings
}

.validate_embeddings <- function(embeddings) {
  n_cells <- NULL
  for (dim_chr in names(embeddings)) {
    dim_int <- as.integer(dim_chr)
    arr <- embeddings[[dim_chr]]
    if (length(dim(arr)) != 2L) {
      stop("X_umap_", dim_int, "d must be a 2D array.")
    }
    if (ncol(arr) != dim_int) {
      stop("X_umap_", dim_int, "d must have exactly ", dim_int, " columns, got ", ncol(arr), ".")
    }
    if (is.null(n_cells)) {
      n_cells <- nrow(arr)
    } else if (nrow(arr) != n_cells) {
      stop("All embeddings must have the same number of cells (rows).")
    }
  }
  if (
    is.null(n_cells) ||
      !is.numeric(n_cells) ||
      length(n_cells) != 1L ||
      n_cells < 1L ||
      n_cells > .Machine$integer.max
  ) {
    stop(
      "Embeddings must contain between 1 and 2,147,483,647 cells.",
      call. = FALSE
    )
  }
  as.integer(n_cells)
}

.normalize_embedding <- function(arr) {
  if (
    !is.matrix(arr) ||
      !is.numeric(arr) ||
      anyNA(arr) ||
      any(!is.finite(arr))
  ) {
    stop(
      "Embedding coordinates must be a finite numeric matrix.",
      call. = FALSE
    )
  }
  axis_mins <- apply(arr, 2, min)
  axis_maxs <- apply(arr, 2, max)
  axis_ranges <- axis_maxs - axis_mins
  max_range <- max(axis_ranges)
  if (!is.finite(max_range) || max_range <= 0) {
    stop(
      "Embedding coordinates must span a positive finite coordinate range.",
      call. = FALSE
    )
  }
  center <- (axis_mins + axis_maxs) / 2
  scale_factor <- 2 / max_range

  centered <- sweep(arr, 2, center, FUN = "-")
  coords <- centered * scale_factor

  list(
    coords = coords,
    info = list(
      original_range = as.numeric(max_range),
      center = as.numeric(center),
      scale_factor = as.numeric(scale_factor)
    )
  )
}

.write_float32_matrix_row_major <- function(path, mat, compression = NULL) {
  .write_float32_vector(path, as.vector(t(mat)), compression = compression)
}

.write_float32_vector <- function(
    path,
    values,
    compression = NULL,
    allow_generated_nan = FALSE
) {
  if (
    !is.logical(allow_generated_nan) ||
      length(allow_generated_nan) != 1L ||
      is.na(allow_generated_nan)
  ) {
    stop("allow_generated_nan must be TRUE or FALSE.", call. = FALSE)
  }
  if (
    !is.numeric(values) ||
      is.object(values) ||
      !is.null(dim(values))
  ) {
    stop(
      "float32 values must be a native numeric vector.",
      call. = FALSE
    )
  }
  has_forbidden_missing <- any(is.na(values) & !is.nan(values))
  if (
    has_forbidden_missing ||
      any(is.infinite(values)) ||
      (!allow_generated_nan && any(is.nan(values)))
  ) {
    stop(
      "float32 values must contain only finite float32 values; generated ",
      "NaN is accepted only when allow_generated_nan is TRUE.",
      call. = FALSE
    )
  }

  float32_max <- (2 - 2^-23) * 2^127
  float32_min_subnormal <- 2^-149
  outside_finite_float32 <- (
    abs(values) > float32_max |
      (values != 0 & abs(values) < float32_min_subnormal)
  )
  if (any(outside_finite_float32, na.rm = TRUE)) {
    stop(
      "Every nonzero finite float32 value must be representable between ",
      "2^-149 and (2 - 2^-23) * 2^127 in absolute magnitude.",
      call. = FALSE
    )
  }

  con <- .binary_connection(path, compression = compression)
  on.exit(close(con), add = TRUE)
  writeBin(as.double(values), con, size = 4L, endian = "little")
  invisible(.final_binary_path(path, compression))
}

.write_float64_vector <- function(path, values, compression = NULL) {
  if (
    !is.double(values) ||
      is.object(values) ||
      !is.null(dim(values)) ||
      anyNA(values) ||
      any(!is.finite(values))
  ) {
    stop(
      "float64 values must be a finite native double vector.",
      call. = FALSE
    )
  }
  con <- .binary_connection(path, compression = compression)
  on.exit(close(con), add = TRUE)
  writeBin(values, con, size = 8L, endian = "little")
  invisible(.final_binary_path(path, compression))
}

.write_uint8 <- function(path, values, compression = NULL) {
  if (
    !(is.integer(values) || is.double(values)) ||
      is.object(values) ||
      !is.null(dim(values)) ||
      anyNA(values) ||
      any(!is.finite(values)) ||
      any(values != floor(values)) ||
      any(values < 0 | values > 255)
  ) {
    stop(
      "uint8 values must be a numeric vector of finite integers in the ",
      "inclusive range 0 to 255.",
      call. = FALSE
    )
  }
  con <- .binary_connection(path, compression = compression)
  on.exit(close(con), add = TRUE)
  raw_vals <- as.raw(as.integer(values))
  writeBin(raw_vals, con, endian = "little")
  invisible(.final_binary_path(path, compression))
}

.write_uint16 <- function(path, values, compression = NULL) {
  con <- .binary_connection(path, compression = compression)
  on.exit(close(con), add = TRUE)
  raw_vals <- .pack_uint16(values)
  writeBin(raw_vals, con, endian = "little")
  invisible(.final_binary_path(path, compression))
}

.write_uint32 <- function(path, values, compression = NULL) {
  con <- .binary_connection(path, compression = compression)
  on.exit(close(con), add = TRUE)
  raw_vals <- .pack_uint32(values)
  writeBin(raw_vals, con, endian = "little")
  invisible(.final_binary_path(path, compression))
}

.final_binary_path <- function(path, compression) {
  if (!is.null(compression)) paste0(path, ".gz") else path
}

.binary_connection <- function(path, compression = NULL) {
  final <- .final_binary_path(path, compression)
  if (!is.null(compression)) {
    return(gzfile(final, open = "wb", compression = compression))
  }
  file(final, open = "wb")
}

.identity_obs_fields_from_compact_manifest <- function(manifest) {
  expected_names <- c(
    "_format",
    "n_points",
    "centroid_outlier_quantile",
    "latent_key",
    "compression",
    "_obsSchemas",
    "_continuousFields",
    "_categoricalFields"
  )
  if (
    !is.list(manifest) ||
      is.null(names(manifest)) ||
      length(names(manifest)) != length(expected_names) ||
      !setequal(names(manifest), expected_names)
  ) {
    stop(
      "obs manifest must contain exactly the current compact_v1 fields.",
      call. = FALSE
    )
  }
  if (!identical(manifest[["_format"]], "compact_v1")) {
    stop("obs manifest must use the current compact_v1 format.", call. = FALSE)
  }

  continuous_fields <- manifest[["_continuousFields"]]
  categorical_fields <- manifest[["_categoricalFields"]]
  if (!is.list(continuous_fields)) {
    stop(
      "compact_v1 obs manifest _continuousFields must be a list.",
      call. = FALSE
    )
  }
  if (!is.list(categorical_fields)) {
    stop(
      "compact_v1 obs manifest _categoricalFields must be a list.",
      call. = FALSE
    )
  }

  identity_fields <- list()
  manifest_keys <- character(0)
  for (field in continuous_fields) {
    if (
      !is.list(field) ||
        !(length(field) %in% c(1L, 3L)) ||
        !is.character(field[[1]]) ||
        length(field[[1]]) != 1L ||
        is.na(field[[1]]) ||
        !nzchar(field[[1]])
    ) {
      stop(
        "compact_v1 continuous observation fields must be exact ",
        "[key] or [key, minValue, maxValue] tuples.",
        call. = FALSE
      )
    }
    key <- field[[1]]
    manifest_keys <- c(manifest_keys, key)
    identity_fields[[length(identity_fields) + 1L]] <- list(
      key = key,
      kind = "continuous"
    )
  }

  for (field in categorical_fields) {
    if (
      !is.list(field) ||
        !(length(field) %in% c(5L, 7L)) ||
        !is.character(field[[1]]) ||
        length(field[[1]]) != 1L ||
        is.na(field[[1]]) ||
        !nzchar(field[[1]]) ||
        !(is.atomic(field[[2]]) || is.list(field[[2]])) ||
        !is.null(dim(field[[2]]))
    ) {
      stop(
        "compact_v1 categorical observation fields must be exact ",
        "five- or seven-member tuples with a category array.",
        call. = FALSE
      )
    }
    key <- field[[1]]
    manifest_keys <- c(manifest_keys, key)
    identity_fields[[length(identity_fields) + 1L]] <- list(
      key = key,
      kind = "category",
      n_categories = as.integer(length(field[[2]]))
    )
  }

  .assert_unique_filename_components(
    manifest_keys,
    what = "Observation field keys"
  )
  identity_fields
}

.write_json <- function(path, payload, pretty = FALSE) {
  json <- jsonlite::toJSON(
    payload,
    auto_unbox = TRUE,
    null = "null",
    digits = 17
  )

  if (isTRUE(pretty)) {
    json <- jsonlite::prettify(json)
  } else if (is.numeric(pretty) && length(pretty) == 1L) {
    json <- jsonlite::prettify(json, indent = as.integer(pretty))
  }

  writeLines(json, con = path, useBytes = TRUE)
  invisible(path)
}

.float32_quantization_chunk_size <- 1048576L

.roundtrip_finite_float32_chunk <- function(values, field_name) {
  encoded <- writeBin(
    as.double(values),
    raw(),
    size = 4L,
    endian = "little"
  )
  rounded <- readBin(
    encoded,
    what = double(),
    n = length(values),
    size = 4L,
    endian = "little"
  )
  if (
    length(rounded) != length(values) ||
      anyNA(rounded) ||
      any(!is.finite(rounded))
  ) {
    stop(
      "Cannot quantize field '",
      field_name,
      "': values must remain finite in the viewer's float32 domain.",
      call. = FALSE
    )
  }
  rounded
}

.quantize_continuous <- function(
    values,
    bits,
    field_name,
    .chunk_size = .float32_quantization_chunk_size
) {
  bits <- .validate_quantization_bits(bits, arg = "bits")
  field_name <- .validate_required_string(field_name, "field_name")
  .chunk_size <- .validate_positive_integer(
    .chunk_size,
    ".chunk_size"
  )
  if (
    !is.numeric(values) ||
      is.object(values) ||
      !is.null(dim(values))
  ) {
    stop(
      "Cannot quantize field '",
      field_name,
      "': values must be a native numeric vector.",
      call. = FALSE
    )
  }
  if (length(values) == 0L) {
    stop(
      "Cannot quantize field '",
      field_name,
      "': it contains no finite values.",
      call. = FALSE
    )
  }

  source_min <- Inf
  source_max <- -Inf
  min_val <- Inf
  max_val <- -Inf
  starts <- seq.int(1L, length(values), by = .chunk_size)
  for (start in starts) {
    end <- min(
      length(values),
      start + as.double(.chunk_size) - 1
    )
    source_chunk <- values[start:end]
    if (anyNA(source_chunk) || any(!is.finite(source_chunk))) {
      stop(
        "Cannot quantize field '",
        field_name,
        "': values must contain only finite values.",
        call. = FALSE
      )
    }
    source_min <- min(source_min, min(source_chunk))
    source_max <- max(source_max, max(source_chunk))
    rounded <- .roundtrip_finite_float32_chunk(
      source_chunk,
      field_name
    )
    min_val <- min(min_val, min(rounded))
    max_val <- max(max_val, max(rounded))
  }

  if (source_min == source_max) {
    stop(
      "Cannot quantize field '",
      field_name,
      "': all values are constant, but compact_v1 quantization ",
      "requires minValue to be less than maxValue.",
      call. = FALSE
    )
  }

  if (min_val == max_val) {
    stop(
      "Cannot quantize field '",
      field_name,
      "': its native-double variation collapses to one value in the ",
      "viewer's float32 domain.",
      call. = FALSE
    )
  }

  if (bits == 8L) {
    max_quant <- 254L
  } else {
    max_quant <- 65534L
  }

  scale <- max_quant / (max_val - min_val)
  quantized <- integer(length(values))
  for (start in starts) {
    end <- min(
      length(values),
      start + as.double(.chunk_size) - 1
    )
    rounded <- .roundtrip_finite_float32_chunk(
      values[start:end],
      field_name
    )
    normalized <- (rounded - min_val) * scale
    normalized[normalized < 0] <- 0
    normalized[normalized > max_quant] <- max_quant
    quantized[start:end] <- as.integer(
      floor(normalized + 1e-8)
    )
  }

  list(
    quantized = quantized,
    min_val = min_val,
    max_val = max_val,
    scale = scale
  )
}

.quantize_nullable_outlier_quantiles <- function(values, bits, field_name) {
  bits <- .validate_quantization_bits(bits, arg = "bits")
  field_name <- .validate_required_string(field_name, "field_name")
  if (
    !is.numeric(values) ||
      is.object(values) ||
      !is.null(dim(values))
  ) {
    stop(
      "Cannot quantize outlier field '",
      field_name,
      "': values must be a native numeric vector.",
      call. = FALSE
    )
  }
  if (any(is.na(values) & !is.nan(values))) {
    stop(
      "Cannot quantize outlier field '",
      field_name,
      "': only generated NaN values may represent missing quantiles.",
      call. = FALSE
    )
  }
  if (any(is.infinite(values))) {
    stop(
      "Cannot quantize outlier field '",
      field_name,
      "': values must contain only finite values or generated NaN.",
      call. = FALSE
    )
  }

  missing_mask <- is.nan(values)
  finite_quantized <- .quantize_continuous(
    values[!missing_mask],
    bits = bits,
    field_name = field_name
  )
  missing_value <- if (bits == 8L) 255L else 65535L
  quantized <- rep(missing_value, length(values))
  quantized[!missing_mask] <- finite_quantized$quantized

  list(
    quantized = quantized,
    min_val = finite_quantized$min_val,
    max_val = finite_quantized$max_val,
    scale = finite_quantized$scale
  )
}

.category_values_and_codes <- function(values) {
  if (is.logical(values) && !is.object(values)) {
    present <- !is.na(values)
    categories <- c(FALSE, TRUE)
    categories <- categories[vapply(
      categories,
      function(category) any(present & values == category),
      logical(1)
    )]
    codes <- match(values, categories) - 1L
    codes[!present] <- -1L
    return(list(categories = categories, codes = codes))
  }

  if (is.factor(values)) {
    categorical <- values
  } else if (is.character(values) && !is.object(values)) {
    categorical <- factor(values)
  } else {
    stop(
      "Categorical observations must be a factor, logical, or character ",
      "vector.",
      call. = FALSE
    )
  }
  codes <- as.integer(categorical) - 1L
  codes[is.na(codes)] <- -1L
  list(
    categories = as.character(levels(categorical)),
    codes = codes
  )
}

.observation_kind <- function(values, key) {
  if (is.factor(values)) {
    return("category")
  }
  if (
    (is.logical(values) || is.character(values)) &&
      !is.object(values)
  ) {
    return("category")
  }
  if (is.numeric(values) && !is.object(values)) {
    return("continuous")
  }
  stop(
    "Observation field '", key,
    "' must be a native numeric, logical, character, or factor vector.",
    call. = FALSE
  )
}

.summarize_obs_field <- function(s, key, obs_continuous_quantization, obs_categorical_dtype) {
  kind <- .observation_kind(s, key)

  if (identical(kind, "continuous")) {
    dtype_str <- if (is.null(obs_continuous_quantization)) {
      "float32"
    } else if (obs_continuous_quantization == 8L) {
      "uint8"
    } else {
      "uint16"
    }
    return(
      list(
        key = key,
        kind = "continuous",
        quantized = !is.null(obs_continuous_quantization),
        quantization_bits = if (!is.null(obs_continuous_quantization)) {
          obs_continuous_quantization
        } else {
          NULL
        },
        dtype = dtype_str
      )
    )
  }

  categories <- .category_values_and_codes(s)$categories
  n_categories <- length(categories)
  dtype_str <- if (identical(obs_categorical_dtype, "uint8")) {
    if (n_categories > 255L) {
      stop(
        "Field '", key, "' has ", n_categories,
        " categories, but uint8 supports at most 255."
      )
    }
    "uint8"
  } else {
    if (n_categories > 65535L) {
      stop(
        "Field '", key, "' has ", n_categories,
        " categories, but uint16 supports at most 65,535."
      )
    }
    "uint16"
  }

  list(
    key = key,
    kind = "category",
    category_count = as.integer(n_categories),
    codes_dtype = dtype_str,
    outlier_quantized = !is.null(obs_continuous_quantization),
    outlier_quantization_bits = if (!is.null(obs_continuous_quantization)) {
      obs_continuous_quantization
    } else {
      NULL
    }
  )
}

.export_obs <- function(
    obs,
    obs_keys,
    latent,
    embeddings,
    obs_binary_dir,
    obs_binary_dirname,
    centroid_outlier_quantile,
    centroid_min_points,
    obs_continuous_quantization,
    obs_categorical_dtype,
    compression
) {
  safe_keys <- .assert_unique_filename_components(obs_keys, what = "obs_keys")
  continuous_fields <- list()
  categorical_fields <- list()
  continuous_dtype_info <- list()
  categorical_dtype_info <- list()

  for (idx in seq_along(obs_keys)) {
    key <- obs_keys[[idx]]
    s <- obs[[key]]
    safe_key <- safe_keys[[idx]]

    kind <- .observation_kind(s, key)

    if (identical(kind, "continuous")) {
      values <- s
      storage.mode(values) <- "double"
      if (length(values) != nrow(obs)) {
        stop("Length mismatch for obs[['", key, "']]: ", length(values), " vs ", nrow(obs))
      }
      if (anyNA(values) || any(!is.finite(values))) {
        stop(
          "Observation field '", key,
          "' must contain only finite values.",
          call. = FALSE
        )
      }

      if (!is.null(obs_continuous_quantization)) {
        q <- .quantize_continuous(values, bits = obs_continuous_quantization, field_name = key)
        ext <- if (obs_continuous_quantization == 8L) "u8" else "u16"
        dtype_str <- if (obs_continuous_quantization == 8L) "uint8" else "uint16"
        value_path <- file.path(obs_binary_dir, sprintf("%s.values.%s", safe_key, ext))
        if (obs_continuous_quantization == 8L) {
          .write_uint8(value_path, q$quantized, compression = compression)
        } else {
          .write_uint16(value_path, q$quantized, compression = compression)
        }
        continuous_fields[[length(continuous_fields) + 1L]] <- list(key, q$min_val, q$max_val)
        if (length(continuous_dtype_info) == 0L) {
          continuous_dtype_info <- list(
            ext = ext,
            dtype = dtype_str,
            quantized = TRUE,
            quantizationBits = obs_continuous_quantization
          )
        }
      } else {
        value_path <- file.path(obs_binary_dir, sprintf("%s.values.f32", safe_key))
        .write_float32_vector(value_path, values, compression = compression)
        continuous_fields[[length(continuous_fields) + 1L]] <- list(key)
        if (length(continuous_dtype_info) == 0L) {
          continuous_dtype_info <- list(ext = "f32", dtype = "float32", quantized = FALSE)
        }
      }

      next
    }

    categorical <- .category_values_and_codes(s)
    categories <- categorical$categories
    codes <- categorical$codes

    n_categories <- length(categories)
    dtype_choice <- if (identical(obs_categorical_dtype, "uint8")) {
      if (n_categories > 255L) {
        stop(
          "Field '", key, "' has ", n_categories,
          " categories, but uint8 supports at most 255."
        )
      }
      list(dtype = "uint8", missing_value = 255L)
    } else {
      if (n_categories > 65535L) {
        stop(
          "Field '", key, "' has ", n_categories,
          " categories, but uint16 supports at most 65,535."
        )
      }
      list(dtype = "uint16", missing_value = 65535L)
    }

    missing_value <- dtype_choice$missing_value
    dtype_str <- dtype_choice$dtype

    codes_typed <- rep(missing_value, length(codes))
    valid_mask <- codes >= 0L
    codes_typed[valid_mask] <- codes[valid_mask]

    if (identical(dtype_str, "uint8")) {
      codes_fname <- sprintf("%s.codes.u8", safe_key)
      codes_path <- file.path(obs_binary_dir, codes_fname)
      .write_uint8(codes_path, codes_typed, compression = compression)
    } else {
      codes_fname <- sprintf("%s.codes.u16", safe_key)
      codes_path <- file.path(obs_binary_dir, codes_fname)
      .write_uint16(codes_path, codes_typed, compression = compression)
    }

    if (is.null(centroid_outlier_quantile)) {
      centroids_by_dim <- stats::setNames(
        lapply(names(embeddings), function(...) list()),
        names(embeddings)
      )
    } else {
      centroids_by_dim <- .compute_centroids_for_all_dimensions(
        embeddings = embeddings,
        codes = codes,
        categories = categories,
        outlier_quantile = centroid_outlier_quantile,
        min_points = centroid_min_points
      )
    }

    outlier_quantiles <- .compute_latent_space_quantiles(
      latent = latent,
      codes = codes,
      categories = categories,
      min_points = centroid_min_points
    )

    if (!is.null(obs_continuous_quantization)) {
      oq <- .quantize_nullable_outlier_quantiles(
        outlier_quantiles,
        bits = obs_continuous_quantization,
        field_name = paste0(key, "_outliers")
      )
      oq_ext <- if (obs_continuous_quantization == 8L) "u8" else "u16"
      oq_dtype_str <- if (obs_continuous_quantization == 8L) "uint8" else "uint16"

      outlier_fname <- sprintf("%s.outliers.%s", safe_key, oq_ext)
      outlier_path <- file.path(obs_binary_dir, outlier_fname)
      if (obs_continuous_quantization == 8L) {
        .write_uint8(outlier_path, oq$quantized, compression = compression)
      } else {
        .write_uint16(outlier_path, oq$quantized, compression = compression)
      }

      categorical_fields[[length(categorical_fields) + 1L]] <- list(
        key,
        I(categories),
        dtype_str,
        as.integer(missing_value),
        centroids_by_dim,
        oq$min_val,
        oq$max_val
      )

      if (length(categorical_dtype_info) == 0L) {
        categorical_dtype_info <- list(
          codesExt = if (identical(dtype_str, "uint8")) "u8" else "u16",
          outlierExt = oq_ext,
          outlierDtype = oq_dtype_str,
          outlierQuantized = TRUE
        )
      }
    } else {
      outlier_fname <- sprintf("%s.outliers.f32", safe_key)
      outlier_path <- file.path(obs_binary_dir, outlier_fname)
      .write_float32_vector(
        outlier_path,
        outlier_quantiles,
        compression = compression,
        allow_generated_nan = TRUE
      )

      categorical_fields[[length(categorical_fields) + 1L]] <- list(
        key,
        I(categories),
        dtype_str,
        as.integer(missing_value),
        centroids_by_dim
      )

      if (length(categorical_dtype_info) == 0L) {
        categorical_dtype_info <- list(
          codesExt = if (identical(dtype_str, "uint8")) "u8" else "u16",
          outlierExt = "f32",
          outlierDtype = "float32",
          outlierQuantized = FALSE
        )
      }
    }
  }

  gz_suffix <- if (!is.null(compression)) ".gz" else ""
  schemas <- list()
  if (length(continuous_dtype_info) > 0L) {
    cont <- list(
      pathPattern = sprintf(
        "%s/{key}.values.%s%s",
        obs_binary_dirname,
        continuous_dtype_info$ext,
        gz_suffix
      ),
      ext = continuous_dtype_info$ext,
      dtype = continuous_dtype_info$dtype,
      quantized = isTRUE(continuous_dtype_info$quantized)
    )
    if (isTRUE(continuous_dtype_info$quantized)) {
      cont$quantizationBits <- as.integer(continuous_dtype_info$quantizationBits)
    }
    schemas$continuous <- cont
  }

  if (length(categorical_dtype_info) > 0L) {
    schemas$categorical <- list(
      codesPathPattern = sprintf("%s/{key}.codes.{ext}%s", obs_binary_dirname, gz_suffix),
      outlierPathPattern = sprintf(
        "%s/{key}.outliers.%s%s",
        obs_binary_dirname,
        categorical_dtype_info$outlierExt,
        gz_suffix
      ),
      outlierExt = categorical_dtype_info$outlierExt,
      outlierDtype = categorical_dtype_info$outlierDtype,
      outlierQuantized = isTRUE(categorical_dtype_info$outlierQuantized)
    )
  }

  list(
    schemas = schemas,
    continuous_fields = continuous_fields,
    categorical_fields = categorical_fields
  )
}

.compute_centroids_for_field <- function(coords, codes, categories, outlier_quantile = 0.95, min_points = 10) {
  if (nrow(coords) != length(codes)) {
    stop("coords and codes must have the same length.")
  }

  outlier_quantile <- .validate_centroid_outlier_quantile(
    outlier_quantile
  )
  if (is.null(outlier_quantile)) {
    stop(
      "outlier_quantile must be a finite number when computing centroids.",
      call. = FALSE
    )
  }

  centroids <- list()
  for (code in seq_along(categories) - 1L) {
    label <- categories[[code + 1L]]
    idx <- which(codes == code)
    n <- length(idx)
    if (n < min_points) {
      next
    }

    pts <- coords[idx, , drop = FALSE]
    center <- colMeans(pts)

    if (n > min_points) {
      diffs <- sweep(pts, 2, center, FUN = "-")
      dists <- sqrt(rowSums(diffs * diffs))
      thr <- as.numeric(stats::quantile(dists, probs = outlier_quantile, names = FALSE, type = 7))
      inlier_mask <- dists <= thr
      n_in <- sum(inlier_mask)
      if (n_in >= min_points) {
        pts_in <- pts[inlier_mask, , drop = FALSE]
        center <- colMeans(pts_in)
        used_count <- n_in
      } else {
        used_count <- n
      }
    } else {
      used_count <- n
    }

    centroids[[length(centroids) + 1L]] <- list(
      category = label,
      position = I(as.numeric(center)),
      n_points = as.integer(used_count)
    )
  }

  centroids
}

.compute_centroids_for_all_dimensions <- function(embeddings, codes, categories, outlier_quantile = 0.95, min_points = 10) {
  result <- list()
  for (dim in names(embeddings)) {
    coords <- embeddings[[dim]]
    result[[dim]] <- .compute_centroids_for_field(
      coords = coords,
      codes = codes,
      categories = categories,
      outlier_quantile = outlier_quantile,
      min_points = min_points
    )
  }
  result
}

.compute_latent_space_quantiles <- function(latent, codes, categories, min_points = 10) {
  n_cells <- nrow(latent)
  quantiles <- rep(NaN, n_cells)

  for (code in seq_along(categories) - 1L) {
    idx <- which(codes == code)
    n <- length(idx)
    if (n < min_points) {
      next
    }
    pts <- latent[idx, , drop = FALSE]
    centroid <- colMeans(pts)
    diffs <- sweep(pts, 2, centroid, FUN = "-")
    dists <- sqrt(rowSums(diffs * diffs))
    ranks <- rank(dists, ties.method = "max")
    quantiles[idx] <- as.numeric(ranks) / n
  }

  quantiles
}

.extract_gene_ids <- function(var, var_gene_id_column) {
  if (
    !is.null(var_gene_id_column) &&
      (
        !is.character(var_gene_id_column) ||
          length(var_gene_id_column) != 1L ||
          is.na(var_gene_id_column) ||
          !nzchar(var_gene_id_column)
      )
  ) {
    stop(
      "var_gene_id_column must be NULL or one non-empty string.",
      call. = FALSE
    )
  }

  if (is.null(var_gene_id_column)) {
    ids <- rownames(var)
    if (is.null(ids)) {
      stop(
        "var has no row names; provide an explicit character gene ID column.",
        call. = FALSE
      )
    }
    .validate_gene_ids(ids)
    return(ids)
  }
  if (!var_gene_id_column %in% names(var)) {
    stop(
      "var_gene_id_column '", var_gene_id_column, "' not found in var. Available columns: ",
      paste(names(var), collapse = ", ")
    )
  }
  ids <- var[[var_gene_id_column]]
  .validate_gene_ids(ids)
  ids
}

.validate_gene_ids <- function(gene_ids) {
  .validate_character_vector(gene_ids, what = "Gene identifiers")

  dup <- unique(gene_ids[duplicated(gene_ids)])
  if (length(dup) > 0L) {
    preview <- paste(sprintf("'%s'", utils::head(dup, 5)), collapse = ", ")
    if (length(dup) > 5L) {
      preview <- paste0(preview, ", ...")
    }
    stop("Gene identifiers must be unique. Duplicates: ", preview, call. = FALSE)
  }

  invisible(gene_ids)
}

.get_gene_column <- function(gene_expression, gene_idx, n_cells) {
  if (inherits(gene_expression, "dgCMatrix")) {
    p <- gene_expression@p
    i <- gene_expression@i
    x <- gene_expression@x

    start <- p[[gene_idx]] + 1L
    end <- p[[gene_idx + 1L]]
    values <- numeric(n_cells)
    if (end >= start) {
      rows <- i[start:end] + 1L
      values[rows] <- x[start:end]
    }
    return(values)
  }

  if (inherits(gene_expression, "Matrix")) {
    if (!requireNamespace("Matrix", quietly = TRUE)) {
      stop("Matrix package is required to export sparse gene_expression objects.")
    }
    dense <- as.matrix(gene_expression[, gene_idx, drop = FALSE])
    return(as.numeric(dense[, 1L]))
  }

  values <- gene_expression[, gene_idx]
  as.numeric(values)
}

.pack_uint16 <- function(values) {
  if (
    !(is.integer(values) || is.double(values)) ||
      is.object(values) ||
      !is.null(dim(values))
  ) {
    stop("uint16 values must be a numeric vector.", call. = FALSE)
  }
  if (anyNA(values) || any(!is.finite(values))) {
    stop("uint16 values must all be finite.", call. = FALSE)
  }
  if (any(values != floor(values))) {
    stop("uint16 values must all be integers.", call. = FALSE)
  }
  if (any(values < 0 | values > 65535)) {
    stop(
      "uint16 values must all be in the inclusive range 0 to 65,535.",
      call. = FALSE
    )
  }
  integer_values <- as.integer(values)
  lo <- as.raw(bitwAnd(integer_values, 0xFFL))
  hi <- as.raw(bitwAnd(bitwShiftR(integer_values, 8L), 0xFFL))
  as.raw(rbind(lo, hi))
}

.pack_uint32 <- function(values) {
  if (
    !(is.integer(values) || is.double(values)) ||
      is.object(values) ||
      !is.null(dim(values))
  ) {
    stop("uint32 values must be a numeric vector.", call. = FALSE)
  }
  if (anyNA(values) || any(!is.finite(values))) {
    stop("uint32 values must all be finite.", call. = FALSE)
  }
  if (any(values != floor(values))) {
    stop("uint32 values must all be integers.", call. = FALSE)
  }
  if (any(values < 0 | values > 4294967295)) {
    stop(
      "uint32 values must all be in the inclusive range 0 to 4,294,967,295.",
      call. = FALSE
    )
  }
  b0 <- as.raw(floor(values) %% 256)
  b1 <- as.raw(floor(values / 256) %% 256)
  b2 <- as.raw(floor(values / 65536) %% 256)
  b3 <- as.raw(floor(values / 16777216) %% 256)
  as.raw(rbind(b0, b1, b2, b3))
}

.connectivity_triplet_values <- function(triplet) {
  if ("x" %in% names(triplet)) {
    return(triplet$x)
  }
  rep.int(1, nrow(triplet))
}

.connectivity_triplet <- function(matrix) {
  triplet_matrix <- if (inherits(matrix, "TsparseMatrix")) {
    matrix
  } else {
    methods::as(matrix, "TsparseMatrix")
  }
  rows <- triplet_matrix@i
  columns <- triplet_matrix@j
  if (length(rows) > 1L) {
    coordinate_order <- order(rows, columns, method = "radix")
    ordered_rows <- rows[coordinate_order]
    ordered_columns <- columns[coordinate_order]
    duplicate_offsets <- which(
      ordered_rows[-1L] == ordered_rows[-length(ordered_rows)] &
        ordered_columns[-1L] == ordered_columns[-length(ordered_columns)]
    )
    if (length(duplicate_offsets) > 0L) {
      duplicate_offset <- duplicate_offsets[[1L]]
      stop(
        "Connectivity contains duplicate sparse coordinates at (",
        ordered_rows[[duplicate_offset]], ", ",
        ordered_columns[[duplicate_offset]], ").",
        call. = FALSE
      )
    }
  }
  Matrix::summary(triplet_matrix)
}

.validate_connectivity_edges <- function(connectivities, n_cells) {
  info <- .connectivity_index_dtype(n_cells)
  expected_shape <- c(n_cells, n_cells)

  if (inherits(connectivities, "Matrix")) {
    if (!requireNamespace("Matrix", quietly = TRUE)) {
      stop("Matrix package is required to validate sparse connectivity matrices.")
    }
    if (!(
      inherits(connectivities, "dMatrix") ||
        inherits(connectivities, "lMatrix") ||
        inherits(connectivities, "nMatrix")
    )) {
      stop(
        "Connectivity values must be real numeric or logical values.",
        call. = FALSE
      )
    }
    if (!identical(as.numeric(dim(connectivities)), as.numeric(expected_shape))) {
      stop(
        "Connectivity matrix shape must exactly match the cell axis: expected (",
        n_cells, ", ", n_cells, "), got (",
        nrow(connectivities), ", ", ncol(connectivities), ").",
        call. = FALSE
      )
    }

    triplet <- .connectivity_triplet(connectivities)
    values <- .connectivity_triplet_values(triplet)
    if (anyNA(values) || any(!is.finite(values))) {
      stop("Connectivity values must all be finite.", call. = FALSE)
    }
    if (any(values < 0)) {
      stop(
        "Connectivity weights must all be non-negative.",
        call. = FALSE
      )
    }
    if (any(values == 0)) {
      stop(
        "Sparse connectivity storage must omit zero-weight coordinates.",
        call. = FALSE
      )
    }
    diagonal_index <- seq_len(n_cells)
    diagonal_values <- connectivities[cbind(diagonal_index, diagonal_index)]
    if (any(diagonal_values != 0)) {
      stop(
        "Connectivity diagonal values must all be exactly zero.",
        call. = FALSE
      )
    }
    if (length(Matrix::which(connectivities != Matrix::t(connectivities))) != 0L) {
      stop("Connectivity matrix must be exactly symmetric.", call. = FALSE)
    }

    upper_triplet <- .connectivity_triplet(
      Matrix::triu(connectivities, k = 1L)
    )
    weights <- as.double(.connectivity_triplet_values(upper_triplet))
    sources <- as.numeric(upper_triplet$i - 1L)
    destinations <- as.numeric(upper_triplet$j - 1L)
  } else {
    if (
      !is.matrix(connectivities) ||
        !(is.numeric(connectivities) || is.logical(connectivities)) ||
        is.object(connectivities) ||
        is.complex(connectivities)
    ) {
      stop(
        "connectivities must be a real numeric or logical matrix or a ",
        "Matrix::Matrix sparse matrix.",
        call. = FALSE
      )
    }
    if (!identical(as.numeric(dim(connectivities)), as.numeric(expected_shape))) {
      stop(
        "Connectivity matrix shape must exactly match the cell axis: expected (",
        n_cells, ", ", n_cells, "), got (",
        nrow(connectivities), ", ", ncol(connectivities), ").",
        call. = FALSE
      )
    }
    if (anyNA(connectivities) || any(!is.finite(connectivities))) {
      stop("Connectivity values must all be finite.", call. = FALSE)
    }
    if (any(connectivities < 0)) {
      stop(
        "Connectivity weights must all be non-negative.",
        call. = FALSE
      )
    }
    if (any(diag(connectivities) != 0)) {
      stop(
        "Connectivity diagonal values must all be exactly zero.",
        call. = FALSE
      )
    }
    if (!all(connectivities == t(connectivities))) {
      stop("Connectivity matrix must be exactly symmetric.", call. = FALSE)
    }

    coordinates <- which(
      upper.tri(connectivities) & connectivities > 0,
      arr.ind = TRUE
    )
    sources <- as.numeric(coordinates[, 1L] - 1L)
    destinations <- as.numeric(coordinates[, 2L] - 1L)
    weights <- as.double(connectivities[coordinates])
  }

  if (length(sources) > 0L) {
    order_index <- order(sources, destinations)
    sources <- sources[order_index]
    destinations <- destinations[order_index]
    weights <- weights[order_index]
  }
  degrees <- tabulate(
    c(sources + 1, destinations + 1),
    nbins = n_cells
  )
  max_neighbors <- if (length(degrees) > 0L) max(degrees) else 0L

  list(
    sources = sources,
    destinations = destinations,
    weights = weights,
    n_edges = length(sources),
    max_neighbors = max_neighbors,
    index_dtype = info$index_dtype,
    index_bytes = info$index_bytes
  )
}

.write_connectivity_edges <- function(connectivity_edges, out_dir, compression) {
  sources_fname <- "edges.src.bin"
  dests_fname <- "edges.dst.bin"
  weights_fname <- "edges.weights.f64.bin"
  sources_path <- file.path(out_dir, sources_fname)
  dests_path <- file.path(out_dir, dests_fname)
  weights_path <- file.path(out_dir, weights_fname)

  if (identical(connectivity_edges$index_dtype, "uint16")) {
    .write_uint16(
      sources_path,
      connectivity_edges$sources,
      compression = compression
    )
    .write_uint16(
      dests_path,
      connectivity_edges$destinations,
      compression = compression
    )
  } else {
    .write_uint32(
      sources_path,
      connectivity_edges$sources,
      compression = compression
    )
    .write_uint32(
      dests_path,
      connectivity_edges$destinations,
      compression = compression
    )
  }
  .write_float64_vector(
    weights_path,
    connectivity_edges$weights,
    compression = compression
  )
  invisible(NULL)
}

.connectivity_index_dtype <- function(n_cells) {
  if (
    !is.numeric(n_cells) ||
      length(n_cells) != 1L ||
      is.na(n_cells) ||
      !is.finite(n_cells) ||
      n_cells <= 0 ||
      n_cells != floor(n_cells)
  ) {
    stop("n_cells must be one positive integer.", call. = FALSE)
  }
  if (n_cells <= 65536) {
    list(index_dtype = "uint16", index_bytes = 2L)
  } else if (n_cells <= 4294967296) {
    list(index_dtype = "uint32", index_bytes = 4L)
  } else {
    stop(
      "Connectivity cannot exceed 4,294,967,296 cells because the current ",
      "browser contract supports at most the complete uint32 index domain.",
      call. = FALSE
    )
  }
}

.export_vector_fields <- function(
    vector_fields,
    embeddings,
    normalization_info,
    out_dir,
    compression,
    vector_field_default
) {
  if (
    !is.list(vector_fields) ||
      is.object(vector_fields) ||
      is.null(names(vector_fields)) ||
      length(vector_fields) == 0L
  ) {
    stop("vector_fields must be one non-empty named list.", call. = FALSE)
  }
  input_names <- names(vector_fields)
  if (anyNA(input_names) || any(!nzchar(input_names))) {
    stop(
      "vector_fields must have native non-empty string names.",
      call. = FALSE
    )
  }
  if (anyDuplicated(input_names)) {
    stop("vector_fields names must be unique.", call. = FALSE)
  }

  grouped <- list()
  for (input_name in input_names) {
    value <- vector_fields[[input_name]]
    if (is.null(value)) {
      stop(
        "Vector field '", input_name, "' cannot be NULL.",
        call. = FALSE
      )
    }

    explicit_match <- regexec(
      "^([A-Za-z0-9][A-Za-z0-9._-]*_umap)_([123])d$",
      input_name
    )
    explicit_parts <- regmatches(input_name, explicit_match)[[1]]
    if (length(explicit_parts) > 0L) {
      field_id <- explicit_parts[[2]]
      declared_dimension <- as.integer(explicit_parts[[3]])
    } else if (
      grepl(
        "^[A-Za-z0-9][A-Za-z0-9._-]*_umap$",
        input_name
      )
    ) {
      field_id <- input_name
      declared_dimension <- NULL
    } else {
      stop(
        "Vector field names must use '<field>_umap' or ",
        "'<field>_umap_<dim>d'.",
        call. = FALSE
      )
    }

    inferred <- .infer_vector_shape(value, input_name)
    dimension <- inferred$dim
    if (
      !is.null(declared_dimension) &&
        declared_dimension != dimension
    ) {
      stop(
        "Vector field '", input_name, "' declares ", declared_dimension,
        "D but contains ", dimension, " components.",
        call. = FALSE
      )
    }
    dimension_key <- as.character(dimension)
    if (!dimension_key %in% names(embeddings)) {
      stop(
        "Vector field '", input_name, "' requires a matching ",
        dimension, "D embedding.",
        call. = FALSE
      )
    }
    if (nrow(inferred$dense) != nrow(embeddings[[dimension_key]])) {
      stop(
        "Vector field '", input_name, "' has ", nrow(inferred$dense),
        " rows; expected ", nrow(embeddings[[dimension_key]]), ".",
        call. = FALSE
      )
    }

    if (is.null(grouped[[field_id]])) {
      grouped[[field_id]] <- list()
    }
    if (!is.null(grouped[[field_id]][[dimension_key]])) {
      stop(
        "vector_fields declares the same field and dimension more than once: ",
        field_id, " ", dimension, "D.",
        call. = FALSE
      )
    }

    normalization <- normalization_info[[dimension_key]]
    scale_factor <- normalization$scale_factor
    if (
      !is.numeric(scale_factor) ||
        length(scale_factor) != 1L ||
        is.na(scale_factor) ||
        !is.finite(scale_factor) ||
        scale_factor <= 0
    ) {
      stop(
        "Vector field '", input_name,
        "' has no exact positive finite embedding scale.",
        call. = FALSE
      )
    }
    grouped[[field_id]][[dimension_key]] <- (
      inferred$dense * scale_factor
    )
  }

  field_ids <- names(grouped)
  folded_ids <- tolower(field_ids)
  if (anyDuplicated(folded_ids)) {
    stop(
      "vector_fields identifiers must be unique under case-insensitive ",
      "filesystem comparison.",
      call. = FALSE
    )
  }

  if (is.null(vector_field_default)) {
    if (length(field_ids) != 1L) {
      stop(
        "vector_field_default is required when more than one vector field ",
        "is supplied.",
        call. = FALSE
      )
    }
    default_field <- field_ids[[1]]
  } else {
    default_field <- .validate_required_string(
      vector_field_default,
      "vector_field_default"
    )
    if (!default_field %in% field_ids) {
      stop(
        "vector_field_default '", default_field,
        "' is not present in vector_fields.",
        call. = FALSE
      )
    }
  }

  vectors_dir <- file.path(out_dir, "vectors")
  .dir_create(vectors_dir)
  fields_meta <- list()
  gz_suffix <- if (!is.null(compression)) ".gz" else ""

  for (field_id in field_ids) {
    dimensions <- sort(as.integer(names(grouped[[field_id]])))
    files <- list()
    for (dimension in dimensions) {
      filename <- sprintf("%s_%dd.bin", field_id, dimension)
      .write_float32_matrix_row_major(
        file.path(vectors_dir, filename),
        grouped[[field_id]][[as.character(dimension)]],
        compression = compression
      )
      files[[sprintf("%dd", dimension)]] <- sprintf(
        "vectors/%s%s",
        filename,
        gz_suffix
      )
    }
    fields_meta[[field_id]] <- list(
      label = field_id,
      available_dimensions = I(dimensions),
      default_dimension = max(dimensions),
      files = files,
      basis = "umap"
    )
  }

  list(
    identity = list(
      default_field = default_field,
      fields = fields_meta
    )
  )
}

.infer_vector_shape <- function(arr, name) {
  if (inherits(arr, "Matrix")) {
    dense <- as.matrix(arr)
  } else if (
    is.numeric(arr) &&
      !is.object(arr) &&
      is.null(dim(arr))
  ) {
    dense <- matrix(arr, ncol = 1L)
  } else if (
    is.matrix(arr) &&
      is.numeric(arr) &&
      !is.object(arr)
  ) {
    dense <- arr
  } else if (
    is.data.frame(arr) &&
      all(vapply(arr, is.numeric, logical(1)))
  ) {
    dense <- as.matrix(arr)
  } else {
    stop(
      "Vector field '", name,
      "' must be a finite real vector or matrix.",
      call. = FALSE
    )
  }
  storage.mode(dense) <- "double"
  if (anyNA(dense) || any(!is.finite(dense))) {
    stop(
      "Vector field '", name, "' must contain only finite values.",
      call. = FALSE
    )
  }
  if (!ncol(dense) %in% c(1L, 2L, 3L)) {
    stop(
      "Vector field '", name, "' must have exactly 1, 2, or 3 components.",
      call. = FALSE
    )
  }
  list(dim = as.integer(ncol(dense)), dense = dense)
}
